* small beauty fixes in logging and code

diff --git a/mulle-platform b/mulle-platform
--- a/mulle-platform
+++ b/mulle-platform
@@ -169,7 +169,7 @@ main()
 
    case "${cmd}" in
       'search')
-         # if you rename command, search for '***' and rename as well
+         # if you rename this command, search for '***' and rename as well
          # shellcheck source=src/mulle-platform-search.sh
          . "${MULLE_PLATFORM_LIBEXEC_DIR}/mulle-platform-search.sh"
 
@@ -177,7 +177,6 @@ main()
       ;;
 
       'translate')
-         # if you rename command, search for '***' and rename as well
          # shellcheck source=src/mulle-platform-translate.sh
          . "${MULLE_PLATFORM_LIBEXEC_DIR}/mulle-platform-translate.sh"
 
@@ -229,7 +228,7 @@ _init()
       then
          if [ -z "`command -v 'mulle-bashfunctions-env'`" ]
          then
-            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
             echo "Fatal Error: Could not find libexec-dir of mulle-bashfunctions-env ($PWD)" >&2
          fi
